# Generated by Django 4.2.7 on 2023-11-29 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AddField(
            model_name='article',
            name='video_text',
            field=models.TextField(default='', verbose_name='Вставка_видео'),
        ),
    ]
